sudo: enabled

language: python

jobs:
  include:
    - os: linux
      env: PYTHON_VERSION=3.6
      dist: xenial
    - os: linux
      env: PYTHON_VERSION=3.7
      dist: xenial
    - os: linux
      env: PYTHON_VERSION=3.8
      dist: xenial
    - os: linux
      env: PYTHON_VERSION=3.6
      dist: bionic
    - os: linux
      env: PYTHON_VERSION=3.7
      dist: bionic
    - os: linux
      env: PYTHON_VERSION=3.8
      dist: bionic
    - os: osx
      language: generic
      env: PYTHON_VERSION=3.6
      osx_image: xcode11.3
    - os: osx
      language: generic
      env: PYTHON_VERSION=3.7
      osx_image: xcode10.3
    - os: osx
      language: generic
      env: PYTHON_VERSION=3.8
      osx_image: xcode9.4
    - os: osx
      language: generic
      env: PYTHON_VERSION=3.6
      osx_image: xcode8.3
    - os: osx
      language: generic
      env: PYTHON_VERSION=3.7
      osx_image: xcode7.3
    - os: osx
      language: generic
      env: PYTHON_VERSION=3.8
      osx_image: xcode6.4

install:
  - pip install --upgrade pip wheel
  - pip install --no-binary pyenv pyenv
  - export PATH=~/.pyenv/bin:$PATH
  - eval "$(pyenv init -)"
  - pyenv install $PYTHON_VERSION
  - pyenv global $PYTHON_VERSION
  - pyenv shell $PYTHON_VERSION
  - pip install --upgrade pip setuptools wheel py
  - python setup.py install

script: pytest --disable-warnings -p no:warnings test/test_aspired.py
