sudo: enabled

language: python

jobs:
  include:
    - os: linux
      env: PYTHON_VERSION=3.6.10
      dist: xenial
    - os: linux
      env: PYTHON_VERSION=3.7.7
      dist: xenial
    - os: linux
      env: PYTHON_VERSION=3.8.2
      dist: xenial
    - os: linux
      env: PYTHON_VERSION=3.6.10
      dist: bionic
    - os: linux
      env: PYTHON_VERSION=3.7.7
      dist: bionic
    - os: linux
      env: PYTHON_VERSION=3.8.2
      dist: bionic
    - os: osx
      language: generic
      env: PYTHON_VERSION=3.6.10
      osx_image: xcode11.3
    - os: osx
      language: generic
      env: PYTHON_VERSION=3.7.7
      osx_image: xcode11.3
    - os: osx
      language: generic
      env: PYTHON_VERSION=3.8.2
      osx_image: xcode11.3
    - os: osx
      language: generic
      env: PYTHON_VERSION=3.6.10
      osx_image: xcode10.3
    - os: osx
      language: generic
      env: PYTHON_VERSION=3.7.7
      osx_image: xcode10.3
    - os: osx
      language: generic
      env: PYTHON_VERSION=3.8.2
      osx_image: xcode10.3

install:
  - unset PYENV_ROOT
  - curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash
  - export PYENV_ROOT="$HOME/.pyenv"
  - export PATH="$PYENV_ROOT/bin:$PATH"
  - eval "$(pyenv init -)"
  - pyenv install $PYTHON_VERSION
  - pyenv global $PYTHON_VERSION
  - pyenv shell $PYTHON_VERSION
  - pip install --upgrade pip setuptools wheel py
  - python setup.py install

script: pytest --disable-warnings -p no:warnings test/test_aspired.py
