sudo: enabled

language: python

jobs:
  include:
    - os: linux
      python: 3.6
      dist: xenial
    - os: linux
      python: 3.7
      dist: xenial
    - os: linux
      python: 3.6
      dist: bionic
    - os: linux
      python: 3.7
      dist: bionic
    - os: osx
      language: generic
      osx_image: xcode11
    - os: osx
      language: generic
      osx_image: xcode11.1
    - os: osx
      language: generic
      osx_image: xcode11.2
    - os: osx
      language: generic
      osx_image: xcode11.3

install:
  - pip3 install --upgrade pip
  - pip3 install --upgrade pytest
  - python3 setup.py install

script: pytest --disable-warnings -p no:warnings test/test_aspired.py
