language: python

jobs:
  include:
    # Ubuntu 2018
    - os: linux
      env: PYTHON_VERSION=3.6.11
      dist: bionic
    - os: linux
      env: PYTHON_VERSION=3.7.8
      dist: bionic
    - os: linux
      env: PYTHON_VERSION=3.8.5
      dist: bionic
    # Ubuntu 2016
    - os: linux
      env: PYTHON_VERSION=3.6.11
      dist: xenial
    - os: linux
      env: PYTHON_VERSION=3.7.8
      dist: xenial
    - os: linux
      env: PYTHON_VERSION=3.8.5
      dist: xenial
    # Catalina (2019)
    - os: osx
      language: generic
      env: PYTHON_VERSION=3.6.11
      osx_image: xcode12u
    - os: osx
      language: generic
      env: PYTHON_VERSION=3.7.8
      osx_image: xcode12u
    - os: osx
      language: generic
      env: PYTHON_VERSION=3.8.5
      osx_image: xcode12u
    # Mojave (2018)
    - os: osx
      language: generic
      env: PYTHON_VERSION=3.6.11
      osx_image: xcode11.3
    - os: osx
      language: generic
      env: PYTHON_VERSION=3.7.8
      osx_image: xcode11.3
    - os: osx
      language: generic
      env: PYTHON_VERSION=3.8.5
      osx_image: xcode11.3
    # High Sierra (2017)
    - os: osx
      language: generic
      env: PYTHON_VERSION=3.6.11
      osx_image: xcode10.1
    - os: osx
      language: generic
      env: PYTHON_VERSION=3.7.8
      osx_image: xcode10.1
    - os: osx
      language: generic
      env: PYTHON_VERSION=3.8.5
      osx_image: xcode10.1

before_install:
  - unset PYENV_ROOT
  - curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash
  - export PYENV_ROOT="$HOME/.pyenv"
  - export PATH="$PYENV_ROOT/bin:$PATH"
  - eval "$(pyenv init -)"
  - pyenv install $PYTHON_VERSION
  - pyenv global $PYTHON_VERSION
  - pyenv shell $PYTHON_VERSION
  - pip install --upgrade pip setuptools wheel py pytest

install:
  - python setup.py install

script: python -m pytest --disable-warnings -p no:warnings test/test_aspired.py
