sudo: enabled

language: python

jobs:
  include:
    - os: linux
      python: 3.6
      dist: xenial
    - os: linux
      python: 3.7
      dist: xenial
    - os: osx
      language: generic
    - os: osx
      language: generic

install:
  - python setup.py install

script: pytest --disable-warnings -p no:warnings -W test/test_aspired.py
