language: python

jobs:
  include:
    # Ubuntu 2018
    - os: linux
      env: PYTHON_VERSION=3.6.10
      dist: bionic
    - os: linux
      env: PYTHON_VERSION=3.7.7
      dist: bionic
    - os: linux
      env: PYTHON_VERSION=3.8.2
      dist: bionic
    # Ubuntu 2016
    - os: linux
      env: PYTHON_VERSION=3.6.10
      dist: xenial
    - os: linux
      env: PYTHON_VERSION=3.7.7
      dist: xenial
    - os: linux
      env: PYTHON_VERSION=3.8.2
      dist: xenial
    # Catalina
    - os: osx
      language: generic
      env: PYTHON_VERSION=3.6.10
      osx_image: xcode11.4
    - os: osx
      language: generic
      env: PYTHON_VERSION=3.7.7
      osx_image: xcode11.4
    - os: osx
      language: generic
      env: PYTHON_VERSION=3.8.2
      osx_image: xcode11.4
    # Mojave
    - os: osx
      language: generic
      env: PYTHON_VERSION=3.6.10
      osx_image: xcode11.3
    - os: osx
      language: generic
      env: PYTHON_VERSION=3.7.7
      osx_image: xcode11.3
    - os: osx
      language: generic
      env: PYTHON_VERSION=3.8.2
      osx_image: xcode11.3
    # High Sierra
    - os: osx
      language: generic
      env: PYTHON_VERSION=3.6.10
      osx_image: xcode10.1
    - os: osx
      language: generic
      env: PYTHON_VERSION=3.7.7
      osx_image: xcode10.1
    - os: osx
      language: generic
      env: PYTHON_VERSION=3.8.2
      osx_image: xcode10.1
    # Sierra
    - os: osx
      language: generic
      env: PYTHON_VERSION=3.6.10
      osx_image: xcode9.2
    - os: osx
      language: generic
      env: PYTHON_VERSION=3.7.7
      osx_image: xcode9.2
    - os: osx
      language: generic
      env: PYTHON_VERSION=3.8.2
      osx_image: xcode9.2
    # El Capitan
    - os: osx
      language: generic
      env: PYTHON_VERSION=3.6.10
      osx_image: xcode8
    - os: osx
      language: generic
      env: PYTHON_VERSION=3.7.7
      osx_image: xcode8
    - os: osx
      language: generic
      env: PYTHON_VERSION=3.8.2
      osx_image: xcode8
  # Some upstream bug as of 2020-05-15
  allow_failures:
    - os: osx
      osx_image: xcode9.2
    - os: osx
      osx_image: xcode8

before_install:
  - unset PYENV_ROOT
  - curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash
  - export PYENV_ROOT="$HOME/.pyenv"
  - export PATH="$PYENV_ROOT/bin:$PATH"
  - eval "$(pyenv init -)"
  - pyenv install $PYTHON_VERSION
  - pyenv global $PYTHON_VERSION
  - pyenv shell $PYTHON_VERSION
  - pip install --upgrade pip setuptools wheel py

install:
  - python setup.py install

script: python -m pytest --disable-warnings -p no:warnings test/test_aspired.py
